# Generated by Django 5.2.3 on 2026-01-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovehub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoveNote',
        ),
    ]
