# Generated by Django 5.2.3 on 2026-01-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovehub', '0002_delete_lovenote'),
    ]

    operations = [
    ]
